apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:091piYeuVvCAYLWUD8nRXty/cGf6IOSvWoWaZP7Z/qQt2itp,iv:mdkMcEKSY8zc/gUupgJvveqGweAjV0g9UFnzo6tI6L8=,tag:+Ll9sRHu/UB9ROpHFrg3WA==,type:str]
    credentials.json: ENC[AES256_GCM,data:oVMXtD6ZBGg2ww+5NIgXHSrE+8RUrlycCNpMbb9LtyuG940GDNLscVe745joA15FfMS91YdIT/2JwKm+LjnplPe/zWG11eEW+3FqVuz8iwqWjCpfzY7s1BGdBZRyjj3vIkDti01qIR3yJmAf1xWmVfD38O1W0UAYEQdh/OM/m6bAOet/5b/GVMuUlrKEryQJe3V1PunCAiwdjL1LHA8GRnUJPZ/AFmkPyGDK1cmb/Q==,iv:hCwAXoI1ii47CXauYswQm5kyjjl/RbqpuqqhlH+9LjA=,tag:AN6drB0HIrkT5/4r/TME8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQkN6MitYelNaY2d2QnRP
            ODBraHg0NFNCK29EMXNMQlpwTjBYWkxaQnl3ClZtaFliYVkrbkYvaitEejhadlZy
            L0F3V2wwV3NWcVI1allHc0pwSnpVMjQKLS0tIFBlWVE1UXJidXR3K3FqTnBzVTNl
            Q3BGOUh5aUppWCsrZVFJbEN1N3VDK0EKI3DSsSok9+zX/Wu8crFuIOp4qN76x+rA
            OfR96dAWHwHRje0mvGYkfCML5rYNOjAEKiJNBOAiMivG+33xSt/sJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T13:29:44Z"
    mac: ENC[AES256_GCM,data:gDNl1r//TGjfUhLZ1eob/rMDdJ9dOq1bdDPocyYjEqKqCLsTtouGvqhnZ4CguowgmoQ/7HKe/10SAuuTvGOYBrRR0ZXAga8056B1usPFQCSKC9N/iao3utuvB4KxxlH7yVMURzwTLAnIFJgCTRrOKpsEwGuFU2Pu//a2whGwLDA=,iv:i8g3x7LxX6ejWQFKkikPqi78z2vi7Gd5E0tfN4euYE8=,tag:jVs3zIpxPzEiFouL7pQRDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
