apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:UDfnwlSVkTZ0BU7+nnuooGM7Nw7y3QtkRtsACxK0MVkvOOEKAcrUdQ==,iv:8WqSPZbJ17KMK3COt3QvFEenwrIMXz1dOSHS5csN/X4=,tag:KVdLIh/weWzDhV8dzrATAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eFk3N2tLNElLRGZ4RjVG
            NVNmQmlINmU2dlloakRSOE5vdFF6aTZxalVZClk0NWZNaHh6czhGTHFqK3g5dGRD
            SlM1T3ptU3lQNWx2QmJITWRDTlZ4aG8KLS0tIHhwN1lWVFNBMzNVVlR4MXY4ZXR5
            SnBJMUlnWHlZTVpHekUvSHY4YjdlRWcKcLrTN8T0MOEJy+HK+pkPiR61x3hu72JD
            HYGkKJoksv55wgviQT058ecfi7osxS9r5KgGmjX2a+FatWCxhhImnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T14:48:38Z"
    mac: ENC[AES256_GCM,data:Leqp0T17ouTq+a2GuP3k+08/w8nMqmIDw/CBK/QqWl3TM6dPP/qGxF1SuT6JAuKMriqTAwXbQFbjVLcnTeoQ9Anhm1yjiM5uszrqP7JPI0VKzu7Fdsq9svMudahGJw9qg8F4E/iXXTnntm5CiNvBwAYWcffXAQWH5I17G3LdSnY=,iv:ZFpPF+km13ggMwUykvoHWi0/Jk7vhbKQ8BorYkh3U7A=,tag:YeUYmEM/OfztmbrPzSbP8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
