apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XPAKC4Xo79TLdu5DgnCVAS6cReRlcEXZP1cliz9KTGNunyGAUXKCew==,iv:rgyLuzyWavWFxvEJp/hi3Sf1k864x1NVBn6cp53y9Hk=,tag:wQ+csVFQfFb3gRjuwGhKiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySFJaZWprbk9La0g0aXZE
            cGRDT1RpTkhEM29JZGJkSGlpMjcydDZHaUMwClIxdzBzWW9JTE9zSXUwYjJKSW1Y
            S2x5eXRSUEJGZ1FuUnZBM2hwTWxlRUkKLS0tIFpkSEpBTG9xeUJzSWlRbTAraTlH
            RnlNU0gwbFBZME8xUTcvb2FCL3dWd00KJL+MXWsM24zAQlDM5QVnCmz9DRILCa9b
            Yb31LDgAKrHfakk28ELWc3FEnBIQJdki1vDkEvmidVqKUL76hph45g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T16:17:28Z"
    mac: ENC[AES256_GCM,data:ca0b9X9uWp3KUwMdfoQ6EDEq2n7jyXxZajrtBTnsJ+VWrYxtCasnSxABNgbKaFRXGdTpkROCVjYX1zvYWiVDJB3jdtokUqfebyd71MAVSP1d497Vkx1dnHXvqHkAqV+3PoVsOzPh8c7OOYpY/JyRKTUvLl3q4VG1fiKkbPN74i4=,iv:vSC7LnJ8cFEidL6ZrQBrdFz8BxXeaaxvIPORj6WHwdA=,tag:vnZk2vcf+bLWmIi0AjyETA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
