apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mZt8BfC0NBu1qiB8,iv:2dHeCd2z9+sn2Bm/HTZ4LWpWCWEue1+fa9OEwrelmVk=,tag:BNHzdh5wUi8k83oIOYIiJg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9IFigjJZaOCznztCKsfG0Ccr,iv:acT4EHGwmdOCLHj95AK5Ep3ACk8+oGecH+2NedJnIbM=,tag:lw1mHKcMV3QXXEyy5md2bg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:I+i3TDpiTBy2Z/dKC/95pqQ/fxem1257CEWACC6LnLGIR7fK,iv:eErMQ0MA00TpMxDCSh4GpAtyhCd8sroPTm7y2q10uAo=,tag:juRRCIqm74xjmyn3euI8Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNXk0ZS8waHFRa1lRbUFW
            Mkw3UUV5Q0FFK1QxV2JwMkp0M1BQTlB3SHdjCnk3akhFNHoxYnhzUVB6NG5GcXpU
            b0N5SEpGT1pmS1NYNFYxbHhIMm5DNHcKLS0tIG1XVFI0WHk2UmUyQXVpTEtIdktR
            Z0kySnhHMDJUYXpobDg4cnlqbVU5WjgKD9LuV6i1S7CO4UK9Bo6Bvl9V6qrbia2+
            c/pua0NQ+6EgzSyCFKnj6eTzsWua3/rVQew5fwI9rjRRP2mnf1Nt1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T22:02:18Z"
    mac: ENC[AES256_GCM,data:ftDBLg2KEwPrNu61ssxHOJiyjbtP+rzeO2XXA0hKL4ncrDUkxY/Mbaw8DIYWHJkymTi6yHYnsJqz45A7xpH9U2YFHs4rajDoF+6M7UW5CgL2zCrnJ1xFVQ10iQyavO5wRYrovgQixWKWqXzdQpsIJhaFnh5AJtqPDC0yQ2ji5pM=,iv:3eottYO0qL8EOYN+oSrFCsPNtGBwY8lR03fUkNjEYNI=,tag:5UZe2cCDK443JQiyZXSwsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
