apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iMHFOVG2AFstLYhG,iv:uHYRx+4eyxCDbKeF7e4LM/cckfNp4hm5VO8GV0QnCHY=,tag:gt7eJzYZqpx5g/ss/Fhk0g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Wh/uqlZmcQeyp+DMI7+dLYvt,iv:Pmal7m9fO72HLM5TI3/xZqC0Jqh+uPAwRXHgf5IpTnM=,tag:GLOw3rUVOnfIQPwo3Bs/ow==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nPOZZkNlTB1VPjlX018ixBTXh5mN8bHbZEagNfrZlzbWvj14,iv:r9hDP+CH8WZNCDlZmcZlHILkE6NZV4K23JA4OZwm9u0=,tag:Z9QQLkmVM6AXbyDPecRj9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TVhXcXRDNkpRcWNNZzdC
            dWVwRzlib2IyNEp5akJqcW8rVmptNFo1UFFjCmFNblFsd2poSk4yd2lmZ3UrVnJ5
            c2hacDZ4Nnd2OTVKaEJCTHFwUGdKQlUKLS0tIHhGZlo5QUcyZWo5alpUYS9ic2d5
            aHFIamhNZTRXYVNHZC8xVU5Wb2RpSkkKJ9lVtOQamhFPEubX2m+21F/3ppQgpmjI
            lHQsil7TUElIsHubxK4ffzxn2NVc/igihokRFfAx61QcCltI06jT0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T14:46:15Z"
    mac: ENC[AES256_GCM,data:zTAXbZ9oygqjNUBCsMsrCgcOKZlk5afnR5SEJHEqgQdHJRfvg8628P0pwLY57/gRpvqj5Xt3rBYaXP37zvv1mKQbVmrHAbIM0aGWwCmtXMPX9bMEjJAGRIHOCcPeirmtbrUHRYnq+QrEVE+iUGTUTzDufk2xjC4hMX1bGSa/Aug=,iv:JVD4ATjnlkkGiElQG+xqGoI7jVlG5j3gZQOAgjV5MhA=,tag:wPcYsJuApmR2ZO2zGpYpdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
