apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xFxPeiUykvtdRyQrJG2OHDIcJONwZLzRn3rJbUn8Nm4=,iv:7S+UkzVg7h6PefWJld+ROwXy/Hws1/roBox4aiyUADc=,tag:a+jkjx1RZTyz2vuZZLpigw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcytZcUkzb1ZTNndvcFhM
            L041OXF2b1d2ZC8zWTVjS29SVHJDSG1oOUQwCkt0R0NzOEJ1bEdpUkFEOGVCR3hM
            K3FKakVxVkdEaVNGT3UzYWhyb25PYVUKLS0tIHVkSlQyUHdyZTdwNzY2MHpjT1Ex
            MEszMXVQYVpXaU00NkZzNUZMbnMwODAKiCmpYSg5EeMDuJchH1ZX8enwmJuSyBXe
            GLtLcnG4PRl+9eSTFhJXseAntuCDfGkbxInj3+OI0DwoSptpLRp0Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T14:48:38Z"
    mac: ENC[AES256_GCM,data:gIrZkX2rLbXk66jDH/eIO86g4nFpgE/usLXXkbC370kkF3dOnUh2b3T9eVb7/jaI6bvTQuHZWKpgmNVSrLz6Xw9vmH3bprEgYlQxt01cwYfU0IaNhGw3V0kWmxSK/UOXtKG3FWJJcUXirDGLA9G2Ey1o2QWHQ26tjCDiXWNf86I=,iv:V0gOJb4z6qVziE7cKtgHRrxTIoJDPEbqGzDLHiAx8mI=,tag:wJGdDhL/NPycMbox+lvVVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
