apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xIHneImFW99qrfjPfeCse5TPovfLJ/7WE8fdObcqJ/a+s1J0rSmkIg==,iv:2GBrSXFXgE7ITTKuWv7RTfJ3ZfV7qlIBK7+JIqJnfdg=,tag:cyDUCGa/vgXeLtAmwrm03A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUG85UjNlZlIwb0diTG5L
            UjZIdENaejV0cjhsK09XbFpZOVBiaVRWWUNJClBrMzM4bnhqSVBtSHMvaExoQW4y
            eVEzdkhoMmp0dnd4SCs3YWxEZmhHNEkKLS0tIE1XSzNkVXJDSzVLT2ZJVE5hNE9I
            TCtqMWhyQjJKQzdaWk52dXJyNk5hZU0K0aCfYua1g3tNtYYtro+tmYQVknZP07D4
            8dmAS9JvxSG8C4z1LHvzl3XRjM56JjOI2Xc+D908PjxPJhUwcSoPFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T13:42:54Z"
    mac: ENC[AES256_GCM,data:GKO4pIqwf0MSybHJr5ztxDNgrz+tem+qcpLqxW8+3tu3KK6H1dUzu/EemJVT6Xe3MjGm7JMbFKhItCC8Saa8OAJTEoButYWGyYoQh7bNbYc4slyJCp++ynx5hpfJzH0hKazg6BtLLTBhezu/Wvs15PcSZNIZrRNnELrxy3jS26g=,iv:glpfOCHff7hamSXp1CMPGexfNMQMdzVIXrAjVnL4Vl4=,tag:vG8rSIcdCeFWCHmVmy513g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
