apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Y5clgQetX/7lrqgv7yxqgYXqMpATBFd7zzAq56OI7aL5BxmSYQ2EDw==,iv:Z03f0VweQoBNBbFnb05ZAcsWMtVizYelY2kL+f6PGTM=,tag:OIH4cJvrQ6HwJWPHfazncQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc0UyUkV1YldmQjljSkFO
            cTNhQzBFKzNReE1lb1lQUGtuRXBKVjNTTUdNCnIvMmVHeURySjVvYVBraGRuelVh
            TnY4cktLdkpaMG1jZ3dNZm9ENWJsb3cKLS0tIDJXSG5UeVdpaFpGc2NLSTIzN2hF
            bmRscGkyL0xmZDRhazN5UjdvNmQyM2sKuTWR7RNgFslt4Vm8XTXVB1DH693OBKMH
            64rQKRZnnU6tuaIWEIN4ymtF/yWWaJmJstvy8fWdo2B2LjMp1011QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T12:32:22Z"
    mac: ENC[AES256_GCM,data:7IEETrkck6urd3bZtudGDBAIwR7/aBY1pfQwvBAkzLM2GLfFShwhyb4GNCxRRRTHHb1jyDOw+FjX3bTxDjvvGEwbLcoFRlqmSVwn6BpdjaEhK6lHNF9JIeU6K9QaVSMwgZMT+IwZ1t6BCGHx/ubfDBjDszrXcnorRJ/tFinDlHY=,iv:YdL6c8eBYAec7kjVcyAsxda1WFRKb6nhd9kQfOKG/lM=,tag:wI9wQujKn3p1SZH0H0b+cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
