apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yPyOvG0WcZ+QsJZXmMCAy6f8bGEp9lKpoP2Fz29YiiowqRQwPyv98w==,iv:Dcf1BDiXjWntkj84TIZbOYdPRpy1TxMUIf7o1Rk1uBQ=,tag:pGItvNM4EsXqB2ERXcjmfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4smh242qwy2szeay6yjxa3favlg8mc73zw4yl67wflgdgvqpseqd8s0nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aUt4V3M1VXVpQlZvejlr
            ZDNldGtla1VDVHVQaGlTSEhuNTA3Q2ttRG5JCmNPRUFSYXFPT050V09ZRGxPMldY
            WDU2eVdxczJPUStjQ3ZPNno0S0dNbWsKLS0tIDZFME9mRHcyaXpjR3hTdCtlVHVx
            cXZQV1pMN3Z0MXhoVzcwUlpYVDVhbDQKKGMyqkyiTH75uE2YkoXy0IihsOOpb1b8
            Pl06CaCWIrnIE+0aQ0pIlk5WU4pDQm4x7nPNOCb3ppXGdk+gCtnbHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T15:31:26Z"
    mac: ENC[AES256_GCM,data:GKcA4vWUMaJbsm8mO8A8ZIevc88mXvHYHH0pAgjEigbaN0ZkVnFX7kknc1+doNUiFBKzFC9/gMZb1QjuqcRdeqTww1ADZC5DOjvYrOxbTztRZ3i8HvuK1ncEitZX79FSFQeKvRgYcIr8XnhECr68SZc4WvAr2UXqDqIb1t196Xs=,iv:+InW6SjsCdZJPr2MBC50G0oIRj5lcJ5Z2/3tzIzs+CA=,tag:Xd03q60ACAkByHLsWzSrMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
